apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    k8s-app: nju13-demo
  name: nju13-demo
  namespace: nju13
spec:
  endpoints:
    - interval: 30s
      port: tcp
      path: /actuator/prometheus
      scheme: 'http'
  selector:
    matchLabels:
      app: nju13-demo
  namespaceSelector:
    matchNames:
      - nju13