apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nju13-demo
  name: nju13-demo
  namespace: nju13
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nju13-demo
  template:
    metadata:
      labels:
        app: nju13-demo
    spec:
      containers:
        - image: harbor.edu.cn/nju13/demo:{VERSION}
          name: demo
---
apiVersion: v1
kind: Service
metadata:
  name: nju13-demo
  namespace: nju13
  labels:
    app: nju13-demo
spec:
  type: NodePort
  selector:
    app: nju13-demo
  ports:
    - name: tcp
      protocol: TCP
      port: 8080
      targetPort: 8080